version: 2
jobs:
  build:
    docker:
      - image: p3din/gltf-blender-io
    steps:
      - checkout
      - run:
          name: Install Blender Plugin (2.79)
          command: rm -rf /opt/blender279/2.79/scripts/addons/io_scene_gltf2 && cp -r addons/io_scene_gltf2 /opt/blender279/2.79/scripts/addons/io_scene_gltf2
      - run:
          name: Install Blender Plugin (2.80)
          command: rm -rf /opt/blender280/2.80/scripts/addons/io_scene_gltf2 && cp -r addons/io_scene_gltf2 /opt/blender280/2.80/scripts/addons/io_scene_gltf2
      - run:
          name: Prepare Tests
          command: cd tests && yarn install
      - run:
          name: Run tests
          command: |
            mkdir -p /out
            cd tests
            OUT_PREFIX=/out yarn test-bail --reporter-options reportDir=/out/mochawesome
      - store_artifacts:
          path: /out
