version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Build docker
          command: docker-compose build
      - run:
          name: Run tests
          command: docker-compose up
      - store_artifacts:
          path: test_out
