version: 2
jobs:
  build:
    docker:
      - image: p3din/gltf-blender-io
    steps:
      - checkout
      - run:
          name: Prepare Tests
          command: cd tests && yarn install
      - run:
          name: Run tests
          command: |
            mkdir -p /out
            cd tests
            OUT_PREFIX=/out yarn test-bail --reporter-options reportDir=/out/mochawesome
      - store_artifacts:
          path: /out
