version: 2
jobs:
  general:
    docker:
      - image: p3din/gltf-blender-io
    steps:
      - checkout
      - run:
          name: Prepare Tests
          command: |
            rm -rf /opt/blender279/2.79/scripts/addons/io_scene_gltf2 && cp -r addons/io_scene_gltf2 /opt/blender279/2.79/scripts/addons/io_scene_gltf2
            rm -rf /opt/blender280/2.80/scripts/addons/io_scene_gltf2 && cp -r addons/io_scene_gltf2 /opt/blender280/2.80/scripts/addons/io_scene_gltf2
            cd tests && yarn install
      - run:
          name: Run tests
          command: |
            mkdir -p /out
            cd tests
            OUT_PREFIX=/out yarn test-bail --reporter-options reportDir=/out/mochawesome -g General
      - store_artifacts:
          path: /out
  exporter:
    docker:
      - image: p3din/gltf-blender-io
    steps:
      - checkout
      - run:
          name: Prepare Tests
          command: |
            rm -rf /opt/blender279/2.79/scripts/addons/io_scene_gltf2 && cp -r addons/io_scene_gltf2 /opt/blender279/2.79/scripts/addons/io_scene_gltf2
            rm -rf /opt/blender280/2.80/scripts/addons/io_scene_gltf2 && cp -r addons/io_scene_gltf2 /opt/blender280/2.80/scripts/addons/io_scene_gltf2
            cd tests && yarn install
      - run:
          name: Run tests
          command: |
            mkdir -p /out
            cd tests
            OUT_PREFIX=/out yarn test-bail --reporter-options reportDir=/out/mochawesome -g Exporter
      - store_artifacts:
          path: /out
  roundtrip:
    docker:
      - image: p3din/gltf-blender-io
    steps:
      - checkout
      - run:
          name: Prepare Tests
          command: |
            rm -rf /opt/blender279/2.79/scripts/addons/io_scene_gltf2 && cp -r addons/io_scene_gltf2 /opt/blender279/2.79/scripts/addons/io_scene_gltf2
            rm -rf /opt/blender280/2.80/scripts/addons/io_scene_gltf2 && cp -r addons/io_scene_gltf2 /opt/blender280/2.80/scripts/addons/io_scene_gltf2
            cd tests && yarn install
      - run:
          name: Run tests
          command: |
            mkdir -p /out
            cd tests
            OUT_PREFIX=/out yarn test-bail --reporter-options reportDir=/out/mochawesome -g Roundtrip
      - store_artifacts:
          path: /out
workflows:
  version: 2
  test:
    jobs:
      - general
      - exporter
      - roundtrip